services:
  cont1:
    container_name: ubuntu1
    hostname: ubuntu1
    tty: true
    build: .
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.10
    dns: 172.24.0.2
    dns_search: .lab.demo
    dns_opt:
     - "no-aaaa"
  cont2:
    container_name: ubuntu2
    hostname: ubuntu2
    tty: true
    build: .
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.11
    dns: 172.24.0.3
    dns_search: .lab.demo
    dns_opt:
     - "no-aaaa"
  web:
    container_name: web
    hostname: web
    image: nginx
    volumes:
    - ./html:/usr/share/nginx/html:ro
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.20
    ports:
    - "80:80"
  primary_dns:
    image: ubuntu/bind9
    hostname: primary_dns
    environment:
      - BIND9_USER=root
      - TZ=Europe/Kiev
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.2
    volumes:
    - ./config_primary:/etc/bind
    - ./cache_primary:/varcache/bind
    restart: unless-stopped
  secondary_dns:
    image: ubuntu/bind9
    environment:
      - BIND9_USER=root
      - TZ=Europe/Kiev
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.3
    volumes:
    - ./config_secondary:/etc/bind
    - ./cache_secondary:/varcache/bind
    restart: unless-stopped

networks:
  okm_ntw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
        