services:
  cont1:
    container_name: ubuntu1
    hostname: ubuntu1
    tty: true
    build: .
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.10
    # dns: 172.24.0.2
    # dns_search: lab.demo
    dns_opt:
     - "no-aaaa"
  cont2:
    container_name: ubuntu2
    hostname: ubuntu2
    tty: true
    build: .
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.11
    # dns: 172.24.0.3
    # dns_search: lab.demo
    dns_opt:
     - "no-aaaa"
  web1:
    container_name: web1
    hostname: web1
    image: nginx
    volumes:
    - ./web/html1:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.21
    ports:
    - "8081:80"
  web2:
    container_name: web2
    hostname: web2
    image: nginx
    volumes:
    - ./web/html2:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.22
    ports:
    - "8082:80"
  web3:
    container_name: web3
    hostname: web3
    image: nginx
    volumes:
    - ./web/html3:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.23
    ports:
    - "8083:80"
  web4:
    container_name: web4
    hostname: web4
    image: nginx
    volumes:
    - ./web/html4:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.24
    ports:
    - "8084:80"
  web5:
    container_name: web5
    hostname: web5
    image: nginx
    volumes:
    - ./web/html5:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.25
    ports:
    - "8085:80"
  primary_dns:
    image: ubuntu/bind9
    hostname: primary_dns
    environment:
      - BIND9_USER=root
      - TZ=Europe/Kiev
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.2
    volumes:
    - ./config_primary:/etc/bind
    - ./cache_primary:/varcache/bind
    restart: unless-stopped
  secondary_dns:
    image: ubuntu/bind9
    environment:
      - BIND9_USER=root
      - TZ=Europe/Kiev
    networks:
      okm_ntw:
        ipv4_address: 172.24.0.3
    volumes:
    - ./config_secondary:/etc/bind
    - ./cache_secondary:/varcache/bind
    restart: unless-stopped

networks:
  okm_ntw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
        